#cloud-config

# Task done here:
# 1- install linux packages
# 2- Create some files
# 3- Execute user cmd
# 4- Kill it self

repo_update: true
repo_upgrade: all

# Write files
${write_files}

# runcmd only runs during the first boot
${comment_runcmd}runcmd:
${comment_change_ssh_port}  - /usr/local/bin/change_ssh_port.sh
${comment_kamikaze}  - sleep ${bastion_lifetime}
${comment_kamikaze}  - shutdown